#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/$REPOSITORY:latest
    restart: on-failure:5
    environment:
      - PORT=$PORT
    ports:
      - "$PORT:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
